name: Monte Carlo Demo CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    
    - name: Lint with flake8
      run: |
        pip install flake8
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
    
    - name: Run tests
      run: |
        pytest tests/ -v --cov=. --cov-report=xml
    
    - name: Validate configuration
      run: |
        python scripts/config.py
      env:
        OPENAI_API_KEY: dummy-key-for-testing
        OPENAI_ORGANIZATION: dummy-org
        OPENAI_PROJECT: dummy-project

  dbt-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dbt
      run: |
        python -m pip install --upgrade pip
        pip install dbt-core dbt-duckdb
    
    - name: Set up dbt profile
      run: |
        mkdir -p ~/.dbt
        cat > ~/.dbt/profiles.yml << 'EOF'
        monte_carlo_dbt:
          target: dev
          outputs:
            dev:
              type: duckdb
              path: './database/monte-carlo.duckdb'
              threads: 4
        EOF

    - name: Create DuckDB database file if missing
      run: |
        mkdir -p database
        python -c "import duckdb; duckdb.connect('database/monte-carlo.duckdb').close()"

    - name: Load test data
      run: |
        pip install pandas duckdb
        python scripts/load_csv.py

    # Add this step here
    - name: List database directory contents
      run: ls -l database
    
    - name: Run dbt
      run: |
        cd monte_carlo_dbt
        dbt run
        dbt test
